name: DEPLOYMENT

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    environment: production
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-versions: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip .dist

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "born2code"
          environment_name: "dev-server"
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: nodejs-app-build.zip

